chore(cache): do not generate cache for macOS build
seems to be causing an error on build - `error[E0463]: can't find crate for `serde_derive` which `pickledb` depends on`